/**
 * AI Self-Healing Agent
 * ─────────────────────────────────────────────────────────────────────────────
 * Reads Playwright's JSON test results, identifies failing tests due to
 * broken selectors / locators, then uses Claude AI to suggest fixed locators
 * by re-inspecting the live page.
 *
 * Usage:
 *   npx ts-node agents/self-healer.ts
 *   npx ts-node agents/self-healer.ts --results ./test-results/results.json
 *
 * Requires:
 *   ANTHROPIC_API_KEY env variable
 *   A Playwright JSON report (generated by running: playwright test --reporter=json)
 */

import Anthropic from '@anthropic-ai/sdk';
import * as fs from 'fs';
import * as path from 'path';
import { chromium } from '@playwright/test';

// ─── Config ──────────────────────────────────────────────────────────────────

const BASE_URL   = 'https://www.saucedemo.com';
const TESTS_DIR  = path.join(__dirname, '..', 'tests');
const REPORT_DIR = path.join(__dirname, '..', 'test-results');

const client = new Anthropic({
  apiKey: process.env.ANTHROPIC_API_KEY,
});

// ─── Types ───────────────────────────────────────────────────────────────────

interface FailedTest {
  title: string;
  file: string;
  error: string;
  failingLine?: string;
}

interface HealSuggestion {
  file: string;
  originalSelector: string;
  suggestedSelector: string;
  reasoning: string;
  confidence: 'high' | 'medium' | 'low';
}

// ─── Parse Failing Tests ──────────────────────────────────────────────────────

function parseFailingTests(): FailedTest[] {
  // Try JSON reporter output first
  const jsonReport = path.join(REPORT_DIR, 'results.json');
  const failures: FailedTest[] = [];

  if (fs.existsSync(jsonReport)) {
    const report = JSON.parse(fs.readFileSync(jsonReport, 'utf-8'));
    const suites = report.suites ?? [];

    const walk = (suite: any) => {
      (suite.specs ?? []).forEach((spec: any) => {
        (spec.tests ?? []).forEach((test: any) => {
          if (test.status === 'failed' || test.status === 'unexpected') {
            const error = test.results?.[0]?.error?.message ?? 'Unknown error';
            failures.push({
              title: spec.title,
              file: suite.file ?? '',
              error,
            });
          }
        });
      });
      (suite.suites ?? []).forEach(walk);
    };
    suites.forEach(walk);
  }

  // If no JSON report, parse spec files for patterns that commonly break
  if (failures.length === 0) {
    console.log('⚠️  No JSON report found. Scanning spec files for risky selectors...');
    const walk = (dir: string) => {
      fs.readdirSync(dir).forEach(f => {
        const full = path.join(dir, f);
        if (fs.statSync(full).isDirectory()) {
          walk(full);
        } else if (f.endsWith('.spec.ts')) {
          const content = fs.readFileSync(full, 'utf-8');
          // Flag tests that use class-based selectors (fragile)
          if (content.match(/\.\w+-\w+/g)) {
            failures.push({
              title: 'Risky class selector detected',
              file: full,
              error: 'Class-based selectors may break when CSS changes',
            });
          }
        }
      });
    };
    walk(TESTS_DIR);
  }

  return failures;
}

// ─── Inspect Live Page ────────────────────────────────────────────────────────

async function getPageDOM(url: string): Promise<string> {
  const browser = await chromium.launch();
  const page    = await browser.newPage();

  await page.goto(BASE_URL);
  await page.fill('[data-test="username"]', 'standard_user');
  await page.fill('[data-test="password"]', 'secret_sauce');
  await page.click('[data-test="login-button"]');
  await page.goto(url);
  await page.waitForLoadState('networkidle');

  // Extract all selectable elements with attributes
  const elements = await page.evaluate(() => {
    const result: string[] = [];
    document.querySelectorAll('*').forEach(el => {
      const tag      = el.tagName.toLowerCase();
      const dataTest = el.getAttribute('data-test');
      const id       = el.getAttribute('id');
      const cls      = el.className;
      const text     = el.textContent?.trim().substring(0, 40);
      if (dataTest || id || text) {
        result.push(JSON.stringify({ tag, dataTest, id, cls, text }));
      }
    });
    return result.slice(0, 100);
  });

  await browser.close();
  return elements.join('\n');
}

// ─── Read Failing Test Source ─────────────────────────────────────────────────

function readTestFile(filePath: string): string {
  const full = path.isAbsolute(filePath)
    ? filePath
    : path.join(TESTS_DIR, filePath);

  if (fs.existsSync(full)) {
    return fs.readFileSync(full, 'utf-8');
  }

  // Try to find by partial name
  let found = '';
  const walk = (dir: string) => {
    fs.readdirSync(dir).forEach(f => {
      const fp = path.join(dir, f);
      if (fs.statSync(fp).isDirectory()) {
        walk(fp);
      } else if (fp.includes(path.basename(filePath))) {
        found = fs.readFileSync(fp, 'utf-8');
      }
    });
  };
  walk(TESTS_DIR);
  return found;
}

// ─── Heal via Claude ──────────────────────────────────────────────────────────

async function healTest(failure: FailedTest): Promise<HealSuggestion[]> {
  console.log(`\n🩺 Analysing failure: "${failure.title}"`);

  const testSource = readTestFile(failure.file);
  if (!testSource) {
    console.log(`   ⚠️  Could not read source file: ${failure.file}`);
    return [];
  }

  // Determine which URL to inspect (heuristic from file path)
  let pageUrl = `${BASE_URL}/inventory.html`;
  if (failure.file.includes('cart'))     pageUrl = `${BASE_URL}/cart.html`;
  if (failure.file.includes('checkout')) pageUrl = `${BASE_URL}/checkout-step-one.html`;

  const liveDom = await getPageDOM(pageUrl);

  const systemPrompt = `You are an expert Playwright test automation engineer.
Your job is to self-heal broken Playwright tests by updating failing selectors.

When given:
1. A failing test's source code
2. The error message
3. The current live DOM elements

You will:
- Identify which selector(s) are likely broken
- Suggest the best replacement selector (prefer data-test attributes)
- Explain your reasoning
- Rate your confidence as high / medium / low

Return a JSON array of suggestions, each with:
{
  "originalSelector": "the old selector string",
  "suggestedSelector": "the new selector string",
  "reasoning": "why this change",
  "confidence": "high|medium|low"
}
Return ONLY valid JSON — no markdown, no explanation outside the JSON.`;

  const userPrompt = `Failing Test:
Title: ${failure.title}
File: ${failure.file}

Error:
${failure.error}

Test Source Code:
\`\`\`typescript
${testSource.substring(0, 4000)}
\`\`\`

Live Page DOM Elements (${pageUrl}):
${liveDom}

Suggest selector fixes.`;

  const message = await client.messages.create({
    model: 'claude-opus-4-5',
    max_tokens: 2048,
    messages: [{ role: 'user', content: userPrompt }],
    system: systemPrompt,
  });

  const raw = message.content
    .filter(b => b.type === 'text')
    .map(b => (b as { type: 'text'; text: string }).text)
    .join('');

  try {
    const suggestions: Omit<HealSuggestion, 'file'>[] = JSON.parse(raw);
    return suggestions.map(s => ({ ...s, file: failure.file }));
  } catch {
    console.log(`   ⚠️  Claude returned non-JSON response for "${failure.title}"`);
    return [];
  }
}

// ─── Apply Suggestions ────────────────────────────────────────────────────────

function applySuggestions(suggestions: HealSuggestion[]): void {
  const byFile: Record<string, HealSuggestion[]> = {};
  suggestions.forEach(s => {
    if (!byFile[s.file]) byFile[s.file] = [];
    byFile[s.file].push(s);
  });

  Object.entries(byFile).forEach(([file, fixes]) => {
    const full = path.isAbsolute(file)
      ? file
      : path.join(TESTS_DIR, file);

    if (!fs.existsSync(full)) {
      console.log(`⚠️  Cannot find file to patch: ${full}`);
      return;
    }

    let content = fs.readFileSync(full, 'utf-8');

    fixes.forEach(fix => {
      if (fix.confidence === 'low') {
        console.log(`   ⏭️  Skipping low-confidence fix for: ${fix.originalSelector}`);
        return;
      }
      if (content.includes(fix.originalSelector)) {
        content = content.replaceAll(fix.originalSelector, fix.suggestedSelector);
        console.log(`   ✅ Fixed [${fix.confidence}]: "${fix.originalSelector}" → "${fix.suggestedSelector}"`);
        console.log(`      Reason: ${fix.reasoning}`);
      }
    });

    fs.writeFileSync(full, content, 'utf-8');
  });
}

// ─── Report ───────────────────────────────────────────────────────────────────

function writeHealReport(all: HealSuggestion[]): void {
  const reportPath = path.join(REPORT_DIR, 'heal-report.json');
  if (!fs.existsSync(REPORT_DIR)) fs.mkdirSync(REPORT_DIR, { recursive: true });
  fs.writeFileSync(reportPath, JSON.stringify(all, null, 2), 'utf-8');
  console.log(`\n📄 Heal report saved to: ${reportPath}`);
}

// ─── CLI Entry Point ──────────────────────────────────────────────────────────

(async () => {
  if (!process.env.ANTHROPIC_API_KEY) {
    console.error('❌ ANTHROPIC_API_KEY environment variable is not set.');
    process.exit(1);
  }

  console.log('🤖 AI Self-Healing Agent starting...\n');

  const failures = parseFailingTests();

  if (failures.length === 0) {
    console.log('🎉 No failing tests found — nothing to heal!');
    process.exit(0);
  }

  console.log(`Found ${failures.length} failing test(s) to analyse.\n`);

  const allSuggestions: HealSuggestion[] = [];

  for (const failure of failures) {
    try {
      const suggestions = await healTest(failure);
      allSuggestions.push(...suggestions);
    } catch (err) {
      console.error(`❌ Error healing "${failure.title}":`, err);
    }
  }

  if (allSuggestions.length === 0) {
    console.log('\n🤷 No selector fixes could be determined.');
    process.exit(0);
  }

  console.log(`\n🔧 Applying ${allSuggestions.length} suggestion(s)...\n`);
  applySuggestions(allSuggestions);
  writeHealReport(allSuggestions);

  console.log('\n✅ Self-healing complete. Run your tests again to verify.');
})();
